name: CI checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check out code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: 1.22.5
      - run: go mod download
      #   - name: Run tests
      #     run: go test ./...
      #   - name: Lint
      #     run: go vet ./...
      - run: go build ./...
    #   - name: Run
    #     run: ./quick-links
